depends_on:
  - eureka-server
  - todos-db

users:
  image: maksimpegov/todo-service-users:latest
  ports:
    - "1002:1002"
  networks:
    - todo-network
  depends_on:
    - eureka-server
    - users-db

todos-db:
  image: postgres:latest
  environment:
    POSTGRES_DB: tododb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: qwer1234
  volumes:
    - pg-todos-data:/var/lib/postgresql/data
  networks:
    - todo-network

users-db:
  image: postgres:latest
  environment:
    POSTGRES_DB: usersdb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: qwer1234
  volumes:
    - pg-users-data:/var/lib/postgresql/data
  networks:
    - todo-network

networks:
  todo-network:

volumes:
  pg-todos-data:
  pg-users-data:
