server:
  port: 8081

spring:
  application:
    name: users

  datasource:
    url: jdbc:postgresql://users-db:5432/usersdb
    username: postgres
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  constraints:
    todos:
      url: http://todos/api/todos
    users:
      url: http://users/api/users
      path: /api/users
    security:
      url: http://api-gateway/api/security
      path: /api/security
    userMicroserviceIdentifier: secret-key

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR

