server:
  port: 8081

spring:
  application:
    name: users
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: postgres
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: create-drop #drop table and create table every time restart
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/