server:
  port: 1003

spring:
  application:
    name: todos

  datasource:
    url: jdbc:postgresql://todos-db:5432/tododb
    username: postgres
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  constraints:
    todos:
      url: http://todos/api/todos
      path: /api/todos

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR

